### PR TITLE
store entities in separate files

### PR DESCRIPTION
**Pull request by derhuerst**

### CODE REVIEW

**Review by juliuste — COMMENTED** [review]
I'd like to keep the option to just run `gemeindeverzeichnis()` to get a combined stream of all entities in all layers.

**Comment by derhuerst** [comment]
Is getting all entities at once really a common use case? What about documenting how to do this using ~~[combined-stream2](https://github.com/joepie91/node-combined-stream2)~~ [multistream](https://github.com/feross/multistream)?

**Comment by juliuste** [comment]
I think it is common enough to include it in the module.

**Review by juliuste — APPROVED** [review]

**Comment by derhuerst** [comment]
Forgot to adapt the docs.

**Pull request merged**
